changed executions to Checkstyle and PMD to run only in code-scan workflow

diff --git a/.github/workflows/code-scan.yml b/.github/workflows/code-scan.yml
--- a/.github/workflows/code-scan.yml
+++ b/.github/workflows/code-scan.yml
@@ -1,8 +1,9 @@
 name: Java code tests
 
 on:
-  schedule:
-    - cron: '0 22 * * 0'
+  push:
+    branches:
+      - daniel/images_fix
 
 jobs:
   build:
@@ -66,15 +67,9 @@ jobs:
       working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.path }}
       continue-on-error: true
 
-    - name: Run Checkstyle
+    - name: Run Checkstyle and PMD
       run: |
-        mvn checkstyle:check > ${{ env.LOGS_PATH }}/${{ matrix.service }}-checkstyle.log 2>&1 || (echo "Checkstyle check failed" >> ${{ env.LOGS_PATH }}/${{ matrix.service }}-checkstyle.log && cat ${{ env.LOGS_PATH }}/${{ matrix.service }}-checkstyle.log)
-      working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.path }}
-      continue-on-error: true
-
-    - name: Run PMD
-      run: |
-        mvn pmd:check > ${{ env.LOGS_PATH }}/${{ matrix.service }}-pmd.log 2>&1 || (echo "PMD check failed" >> ${{ env.LOGS_PATH }}/${{ matrix.service }}-pmd.log && cat ${{ env.LOGS_PATH }}/${{ matrix.service }}-pmd.log)
+        mvn checkstyle:check pmd:check > ${{ env.LOGS_PATH }}/${{ matrix.service }}-code-quality.log 2>&1 || (echo "Checkstyle or PMD check failed" >> ${{ env.LOGS_PATH }}/${{ matrix.service }}-code-quality.log && cat ${{ env.LOGS_PATH }}/${{ matrix.service }}-code-quality.log)
       working-directory: ${{ env.MICROSERVICES_PATH }}/${{ matrix.path }}
       continue-on-error: true
 
